# Generated by Django 3.2.3 on 2021-05-22 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('en_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('area', models.CharField(max_length=20)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('face_encodes', models.BinaryField(default=b'')),
            ],
        ),
    ]
